In [ ]:
#prueba

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("datos_examen.csv")

In [6]:
df[df["Tag"]=="Examen_Carlos"]

             TS            Tag      Value
5    2024-01-01  Examen_Carlos  37.106814
22   2024-01-02  Examen_Carlos  60.441470
39   2024-01-03  Examen_Carlos  80.621933
56   2024-01-04  Examen_Carlos  59.121363
73   2024-01-05  Examen_Carlos   3.279310
90   2024-01-06  Examen_Carlos  13.527029
107  2024-01-07  Examen_Carlos  82.634555
124  2024-01-08  Examen_Carlos  94.451389
141  2024-01-09  Examen_Carlos  81.951723
158  2024-01-10  Examen_Carlos  26.582185
175  2024-01-11  Examen_Carlos   6.316800
192  2024-01-12  Examen_Carlos  87.636722
209  2024-01-13  Examen_Carlos  45.407783
226  2024-01-14  Examen_Carlos  30.616732
243  2024-01-15  Examen_Carlos  52.062572
260  2024-01-16  Examen_Carlos  64.799362
277  2024-01-17  Examen_Carlos  45.107164
294  2024-01-18  Examen_Carlos  99.920113
311  2024-01-19  Examen_Carlos  95.123653
328  2024-01-20  Examen_Carlos  49.140653
345  2024-01-21  Examen_Carlos  82.324578
362  2024-01-22  Examen_Carlos  65.038227
379  2024-01-23  Examen_Carlos  65.459721
396  2024-01-24  Examen_Carlos   6.065231
413  2024-01-25  Examen_Carlos  98.927338
430  2024-01-26  Examen_Carlos  88.738846
447  2024-01-27  Examen_Carlos  22.987007
464  2024-01-28  Examen_Carlos  68.452170
481  2024-01-29  Examen_Carlos  54.492994
498  2024-01-30  Examen_Carlos  41.896129
515  2024-01-31  Examen_Carlos  74.223749
532  2024-02-01  Examen_Carlos  96.691537
549  2024-02-02  Examen_Carlos  71.004221
566  2024-02-03  Examen_Carlos  64.103852
583  2024-02-04  Examen_Carlos  51.040319
600  2024-02-05  Examen_Carlos   1.007010
617  2024-02-06  Examen_Carlos  30.541435
634  2024-02-07  Examen_Carlos  58.188928
651  2024-02-08  Examen_Carlos  23.298443
668  2024-02-09  Examen_Carlos   1.975711
685  2024-02-10  Examen_Carlos  14.137408
702  2024-02-11  Examen_Carlos   1.396352
719  2024-02-12  Examen_Carlos  49.540359
736  2024-02-13  Examen_Carlos  22.527448
753  2024-02-14  Examen_Carlos  32.455702
770  2024-02-15  Examen_Carlos  33.419044
787  2024-02-16  Examen_Carlos  80.653199
804  2024-02-17  Examen_Carlos  20.252099
821  2024-02-18  Examen_Carlos  42.964877
838  2024-02-19  Examen_Carlos  41.292684
855  2024-02-20  Examen_Carlos  19.024427
872  2024-02-21  Examen_Carlos  10.190839
889  2024-02-22  Examen_Carlos  76.553447
906  2024-02-23  Examen_Carlos  70.549350
923  2024-02-24  Examen_Carlos  98.386198
940  2024-02-25  Examen_Carlos  30.345496
957  2024-02-26  Examen_Carlos  54.138923
974  2024-02-27  Examen_Carlos  15.556009
991  2024-02-28  Examen_Carlos  13.476585

In [7]:
df["TS"]=pd.to_datetime(df["TS"])

In [8]:
def leer_df(nombre_csv):
    df=pd.read_csv("nombre_csv")
    df["TS"]=pd.to_datetime(df["TS"])
    return df

In [10]:
def filtro_media(df):
    media_filtrado=df[df["Tag"]=="Examen_Carlos"]["Value"].mean()
    return media_filtrado